@startuml talker_listener

frame "Publisher/Subscriber" {
class talker <<node>> {
  +publisher("topic")
  +timer
  +timer_callback()
}

class listener <<node>> {
  +subscription("topic")
  +listner_callback()
}

talker -right-> listener
}

frame "Service/Client" {
class service <<node>> {
  +add_two_ints service
  +add_two_ints_callback()
}

class client <<node>> {
  +add_two_ints client
  +send_request()
}

client -left-> service : request
service -right-> client : response
}

@enduml
